Use composite action instead of docker

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,8 +4,41 @@ branding:
   icon: check-circle
   color: green
 runs:
-  using: docker
-  image: Dockerfile
+  using: "composite"
+  steps:
+    - name: "Wait for MySQL"
+      run: |
+        MYSQL="mysql --defaults-file=.my.cnf"
+  
+        # Wait for MySQL to start"
+        i=0; while [ $((i+1)) -lt 30 ] && [ ! $($MYSQL -Nse "SELECT VERSION();") ]
+        do
+            echo "Waiting for MySQL... $i"
+            sleep 1;
+        done
+        [ "$i" == "30" ] && echo "Failed to connect to mysql." && exit 1
+      shell: bash
+    - name: "Import DB Snapshots"
+      run: |
+        MYSQL="mysql --defaults-file=.my.cnf"
+        for ENTRY in $(echo "$INPUT_DATABASES" | jq -c .[]); do
+            db=$(echo "$ENTRY" | jq -r .db)
+            s3Uri=$(echo "$ENTRY" | jq -r .s3Uri)
+            dumpFile=$(basename "$s3Uri")
+            aws s3 cp "$s3Uri" "./$dumpFile"
+            [ ! -f "$dumpFile" ] && echo "Failed to download $dumpFile" && exit 1
+            echo "Creating $db"
+            $MYSQL -e "DROP DATABASE IF EXISTS $db; CREATE DATABASE $db;" || exit 1
+            echo "Importing $db from file '${dumpFile}'"
+            if [[ "$dumpFile" == *.gz ]]; then
+                gunzip -c "$dumpFile" | $MYSQL $db
+            else
+                cat "$dumpFile" | $MYSQL $db
+            fi
+        done
+        echo "Cleaning up .mysql-import-from-s3 dir..."
+        rm -rf .mysql-import-from-s3
+      shell: bash
 inputs:
   databases:
     description: Space-delimited list of databases
